#!/bin/bash
container_name=serverb
echo -e "\e[1;31m setting up lab ..../ \e[0m"
docker rm -f $container_name >& /dev/null
docker run -itd --name $container_name mitrasonu/users-review >& /dev/null
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}'  $container_name | xargs echo From your workstation, open an SSH session to 
